import './main.module'
import './main.config'
import './main.run'

import './collections/**/*.js'
import './components/**/*.js'
import './controllers/**/*.js'
import './directives/**/*.js'
import './filters/**/*.js'
import './services/**/*.js'
import './translations/**/*.js'
