import './main.module'
import './main.config'
import './main.run'

import '../../core/javascripts/main'
import '../../admin/javascripts/main'
import '../../member/javascripts/main'
import '../../admin-booking/javascripts/main'
import '../../services/javascripts/main'
import '../../events/javascripts/main'


import './calendar/**/*.js'
import './check-in/**/*.js'
import './clients/**/*.js'
import './config-iframe/**/*.js'
import './core/**/*.js'
import './dashboard-iframe/**/*.js'
import './login/**/*.js'
import './logout/**/*.js'
import './members-iframe/**/*.js'
import './publish-iframe/**/*.js'
import './reset-password/**/*.js'
import './settings-iframe/**/*.js'
